### ISSUE TITLE
Fix Travis Markdown lint configuration

### ISSUE THREAD

**Issue by krook** [Call-for-Code/Project-Sample#19]
Looks like something changed in a recent `markdownlint-cli` version. 

It's not immediately obvious to me what the issue is. 

Not critical either, but @jjasghar if you have a sec to look that would be appreciated.

Otherwise we can just remove the Travis config.

https://travis-ci.com/github/Call-for-Code/Project-Sample/builds/189043731

**Comment by jjasghar** [comment]
Will do!

**Comment by krook** [comment]
Tap tap @jjasghar :)

**Comment by jjasghar** [comment]
Opps, dropped the ball on this. I'll get this resolved asap.

**Comment by krook** [comment]
I'm now more interested in your (@jjasghar) latest ideas on how to make this a great starter template repo for CFC 2021 participants. Not in search of anything too advanced, but are we missing any quick hit best practices for starting a new open source project?

**Comment by krook** [comment]
Removed the Travis stuff, so no longer relevant.
